; Общие настройки для обеих плат
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
; PlatformIO сам скачает эти библиотеки, их не нужно устанавливать руками!
lib_deps =
    arduino-libraries/ArduinoMqttClient
    adafruit/Adafruit NeoPixel


; ================================================
; 1. Настройки для Waveshare ESP32-S3-Zero (4MB/2MB)
; ================================================
[env:waveshare_zero]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM

; ================================================
; 2. Настройки для ESP32-S3-WROOM-1-N16R8 (16MB/8MB)
; ================================================
[env:esp32s3_n16r8]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM